<a href="https://colab.research.google.com/github/bigboom1253/e_commerce_recommendation_system_development/blob/master/Data_preprocessing/Review_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from wordcloud import WordCloud
from collections import Counter
import datetime

plt.rc('font', family='NanumBarunGothic')

In [138]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [139]:
path = "/content/drive/My Drive/최강1조-추천 시스템/데이터 수집/"

# prod = pd.read_json(path + "all_prod_data.json")
review = pd.read_json(path + "all_review_data.json")
# satisfaction = pd.read_json(path + "all_satisfaction_data.json")

# Review

In [142]:
from datetime import datetime

def to_datetime(x):
    if x != "": return datetime.strptime(x[:10], "%Y-%m-%d")

review["review_date"] = review.review_date.apply(lambda x: to_datetime(x)) # 전처리 - datetime 형태 변환
review = review.merge(prod[['prod_idx', 'category_num', 'title', 'small_category']]) # 전처리 - 카테고리 넘버 merge 시켜줌

In [284]:
review = review.dropna()

In [285]:
word = review[['content', 'prod_satis', 'ship_satis']]
word

                                                   content  ...  ship_satis
0                                     생각보다 조금 얇지만 맛있게 먹을게요  ...           5
1                                          배송빠르고  맛도 괜찮아요.  ...           5
2                                            달지도 않고 퍽퍽...   ...           3
3                                            맛있어요 ㅋㅋㅋ 저렴해요  ...           4
4                    싱싱하고 크기도 좋아요 근데 맛이 좀 덜들었네요좀난뒀다 먹어야겠어요  ...           5
...                                                    ...  ...         ...
1695505                                  포장은 꼼꼼한데 냉동이 왔어요   ...           5
1695507  제가 먹어본건 아니구요  명절선물로 롯데 백화점에서진열상품확인후 온라인배송했습니다가...  ...           4
1695510                              맛있게 잘먹어서 다시 구매할 예정입니다  ...           5
1695511                                      잘 받았어요.......  ...           5
1695512                                 아주 좋아요.소포장이라 더 좋네요  ...           5

[1285595 rows x 3 columns]

In [286]:
word['length'] = word.content.apply(len)
word

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                                                   content  ...  length
0                                     생각보다 조금 얇지만 맛있게 먹을게요  ...      20
1                                          배송빠르고  맛도 괜찮아요.  ...      15
2                                            달지도 않고 퍽퍽...   ...      13
3                                            맛있어요 ㅋㅋㅋ 저렴해요  ...      13
4                    싱싱하고 크기도 좋아요 근데 맛이 좀 덜들었네요좀난뒀다 먹어야겠어요  ...      37
...                                                    ...  ...     ...
1695505                                  포장은 꼼꼼한데 냉동이 왔어요   ...      17
1695507  제가 먹어본건 아니구요  명절선물로 롯데 백화점에서진열상품확인후 온라인배송했습니다가...  ...      92
1695510                              맛있게 잘먹어서 다시 구매할 예정입니다  ...      21
1695511                                      잘 받았어요.......  ...      13
1695512                                 아주 좋아요.소포장이라 더 좋네요  ...      18

[1285595 rows x 4 columns]

In [357]:
def clean(x):
    text = re.sub('[-=_+,#\?;:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》☆★×♡♥·ᆢ\/]', '', x) # 특수문자 제거
    text = re.sub('[a-zA-Z]', '', text) # 영어 제거
    text = re.sub('[ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣ]', '', text) # 모음 제거
    text = re.sub('[ㄱ-ㅎ]*', '', text) # 자음 반복 제거
    text = re.sub('[0-9]{3,}', '', text) # 숫자 3번 이상 나오면 제거
    return text

In [358]:
word['clean'] = word.content.apply(clean)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [359]:
word['length_clean'] = word.clean.apply(len)
word

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                                                   content  ...  length_clean
0                                     생각보다 조금 얇지만 맛있게 먹을게요  ...            20
1                                          배송빠르고  맛도 괜찮아요.  ...            14
2                                            달지도 않고 퍽퍽...   ...            10
3                                            맛있어요 ㅋㅋㅋ 저렴해요  ...            10
4                    싱싱하고 크기도 좋아요 근데 맛이 좀 덜들었네요좀난뒀다 먹어야겠어요  ...            37
...                                                    ...  ...           ...
1695505                                  포장은 꼼꼼한데 냉동이 왔어요   ...            17
1695507  제가 먹어본건 아니구요  명절선물로 롯데 백화점에서진열상품확인후 온라인배송했습니다가...  ...            92
1695510                              맛있게 잘먹어서 다시 구매할 예정입니다  ...            21
1695511                                      잘 받았어요.......  ...             6
1695512                                 아주 좋아요.소포장이라 더 좋네요  ...            17

[1285595 rows x 6 columns]

In [360]:
word[word.length_clean == 0]

                       content  prod_satis  ...  clean  length_clean
33                ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ           1  ...                    0
329               good!~~~~~~~           5  ...                    0
514               ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ           1  ...                    0
635                ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ           5  ...                    0
780              ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ           5  ...                    0
...                        ...         ...  ...    ...           ...
1694539             ㅣㅣㅣㅣㅣㅣㅣㅣㅣㅣ           5  ...                    0
1694541          ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ           5  ...                    0
1694914             ,,,,,,,,,,           5  ...                    0
1694961             ㄱㄴㄱㄴㄱㄴㄱㄴㄱㄴ           4  ...                    0
1694991  Axcehtykyhthrhnehevvs           4  ...                    0

[9791 rows x 6 columns]

In [361]:
word[word.length_clean == 1]

                 content  prod_satis  ship_satis  length clean  length_clean
929      gòooooooooooood           5           4      15     ò             1
1393        ㅎㅎㅎㅎㅎㅎㅎㅎ호ㅗㅗㅗ           4           4      12     호             1
1455        굿~~~~~~~~~~~           5           4      12     굿             1
2293        op;''/ jkioo           5           4      12                   1
2750         굿~~~~~~^^^^           4           4      11     굿             1
...                  ...         ...         ...     ...   ...           ...
1693823     굳~~~~~~~~^~~           5           5      12     굳             1
1693960   ㄷㅅㄴㅅㆍㅅㆍㅅㄷㅅㄷㅅㆍㅅ           4           5      15                   1
1694944       굿!!!!!!!!!           5           5      10     굿             1
1694945       굿!!!!!!!!!           5           5      10     굿             1
1695220       굿!!!!!!!!!           5           5      10     굿             1

[2535 rows x 6 columns]

In [362]:
word[word.length_clean == 2]

                     content  prod_satis  ...  clean  length_clean
109               굿굿!!!!!!!!           3  ...     굿굿             2
129              굿굿!!!!!!!!!           4  ...     굿굿             2
1681              ㄱㄹㅁ읏ㄹㄴ낙ㄱㅁㅎ           2  ...     읏낙             2
1943         very delicious            5  ...                    2
2516            별로..........           1  ...     별로             2
...                      ...         ...  ...    ...           ...
1689814   Delicious and good           5  ...                    2
1689837   Delicious and good           5  ...                    2
1691323        ㄷㅈ늑ㅂㅈㅇㅇㅇㅇ으ㅇㅈㅅ           4  ...     늑으             2
1691873  Xbnyek74krvjfymrumt           4  ...     74             2
1694422     ..............             4  ...                    2

[1298 rows x 6 columns]

In [363]:
np.unique(word[word.length_clean == 3].clean)

array(['   ', '  3', '  6', '  7', '  ù', '  굿', '  머', '  흗', ' 55',
       ' 76', ' 9 ', ' 븍지', ' 실망', ' 쓰 ', ' 조앙', ' 존맛', ' 츄 ', '0제즈',
       '1  ', '12호', '2긔니', '2아요', '4”’', '5  ', '6듢든', '6튜푸', '7 8',
       '77퍼', '89 ', 'û55', 'ᆞᆞᆞ', 'ᆞ으응', 'Ỳ67', '⁷  ', '가가가', '가격짱',
       '가뒧두', '가성비', '간쥑뉘', '감사 ', '감사링', '감사요', '갓순필', '강추요', '개꿀맛',
       '개존맛', '갡디늣', '갸어내', '고찮음', '곻고솦', '괘찮음', '괜찮길', '괜찮음', '괜춘요',
       '구 굿', '구8스', '구국국', '구숙궄', '구웃웃', '국굿굿', '굳  ', '굳 디', '굳 횻',
       '굳11', '굳굳 ', '굳굳굳', '굳밤 ', '굳짗짖', '굿  ', '굿굯근', '굿굿 ', '굿굿굿',
       '굿뜨요', '굿이요', '굿이쥬', '굿잡 ', '굿푸짐', '굿호호', '규규규', '그그긪', '그냥 ',
       '그냥요', '그니특', '극그극', '극긔극', '극니그', '극브븝', '극지짇', '근굿굿', '근너느',
       '근버는', '글그는', '급급긋', '급듯7', '긋  ', '긋긋 ', '긋니싲', '긔니그', '긘득그',
       '긪■∫', '기  ', '기기읟', '기너우', '기보너', '기보노', '기보니', '기보련', '기보보',
       '기본마', '깁낍핀', '깁읃빕', '꿀맛탱', '나서 ', '내내넌', '냄새가', '냐채텩', '너나마',
       '너난넌', '너눙5', '너마머', '너웅니', '넘맛 ', '넘작다', '네여 ', '노가가', '노녹4',
       '녹그시', '녹아서', '녿녿밯', '놉넌5', '놓아용', '눅눅함', '뉴너퓨', '뉴수귣', '뉸2좀',
       '느끼함', '느늳디', '느딥닉', '느려요', '느림웅', '느븐브', '느승디', '는느느', '늣는는',
       '늦게옴', '늦늦스', '늪브는', '늫아요', '닂그칟', '다녹음', '단골 ', '달고나', '달다 ',
       '달아요', '대실망', '대용량', '대존맛', '더뇍고', '데데도', '돈아욫', '돟아요', '됴됴러',
       '둓느보', '뒤피뒥', '뒷둫비', '드그극', '드둓드', '드듹니', '드즈즞', '득곡그', '득브극',
       '든프븐', '듢됴나', '듯맛남', '등으응', '듷즛스', '듸시시', '디디그', '디디극', '디디띠',
       '디슨극', '디싱디', '딛디디', '딧중둥', '딧지딛', '땡큐요', '떡볶이', '똥맛남', '똫가굑',
       '라하롷', '라하리', '라히히', '로 쇼', '로어요', '로쳐햐', '롱노후', '롱콬옹', '롸퓨휴',
       '료혀9', '루루루', '르거그', '리외화', '링리리', '마싯케', '마오허', '마이써', '만족 ',
       '만족도', '만족드', '만족쓰', '만족함', '만족힌', '많아요', '맛나게', '맛나뇨', '맛나닿',
       '맛나여', '맛나염', '맛나영', '맛나요', '맛나욕', '맛나용', '맛나욬', '맛나욮', '맛나욯',
       '맛나유', '맛나윻', '맛남 ', '맛남요', '맛노처', '맛도리', '맛어요', '맛없어', '맛없음',
       '맛이 ', '맛이어', '맛이좀', '맛잇다', '맛잇슴', '맛잇음', '맛잇졍', '맛있네', '맛있넹',
       '맛있다', '맛있당', '맛있슈', '맛있어', '맛있엉', '맛있요', '맛있음', '맛있쪄', '맛좋고',
       '맛좋다', '맛좋음', '맛좋응', '맛최고', '맜으슿', '매번굿', '매워요', '맵네요', '먹기전',
       '먹아산', '몁니8', '모뮤묪', '몸노몬', '몽  ', '미머노', '밋나요', '밥도둑', '밧드8',
       '배송굿', '배송이', '베리굿', '별로 ', '별로임', '별루 ', '별루요', '보통 ', '보통요',
       '보통임', '봐보버', '부채살', '브르븐', '븍디스', '비비곡', '비싸 ', '비싸요', '빠리옴',
       '빨라요', '사과는', '사진하', '사힙다', '상품굿', '상풍0', '새우가', '샤브용', '선물함',
       '설탕 ', '소곤골', '소교셔', '솰우푸', '쇄풜서', '쇼됴뇨', '쇼여요', '수구봅', '술안주',
       '스느늡', '스느늣', '스닉눈', '스스슺', '스슫스', '스슷슷', '스흣듯', '슥그굿', '슨분슷',
       '슨슨뜯', '승3듯', '시닏닛', '시시시', '시시싯', '싲붓빋', '싸네요', '쏘쏘 ', '쏘쏘닛',
       '쏘쏘케', '아맛이', '아쉬룸', '아쉬움', '아쉽다', '아오슷', '아요 ', '아조금', '아좋음',
       '아직요', '앗딛싯', '앟있엄', '야용 ', '예뻐용', '예싸게', '옛날는', '오다젝', '오라오',
       '오래돽', '오러허', '오오려', '옹퐃푸', '외허호', '요톸호', '우왕어', '웁느밥', '으으음',
       '은느은', '은은븐', '읃직드', '음 음', '이가나', '이런걸', '이리리', '이지잊', '인극디',
       '읻소솟', '일없소', '일호호', '입니다', '입니닿', '잇슷힏', '있아욯', '작네요', '작아요',
       '잘받았', '잘샀어', '잡내 ', '잦잦진', '재구매', '재구맿', '재주문', '저렴히', '저아여',
       '저아요', '적당히', '젛아여', '젛아요', '젛아욯', '져0류', '조라요', '조싸요', '조아눃',
       '조아료', '조아여', '조아엳', '조아영', '조아오', '조아요', '조아욕', '조아욤', '조아욥',
       '조아용', '조아욯', '조아유', '조아윤', '조아융', '조아툐', '조아혀', '조야오', '조야요',
       '조어요', '조어용', '조와요', '조음 ', '조이요', '조인존', '조타 ', '조하옇', '조하요',
       '조하용', '조하욬', '조항요', '조항용', '조힝요', '존마탱', '존맛 ', '존맛탱', '졸아요',
       '졸얻로', '좀짜요', '종아옿', '종아요', '종하요', '좋네여', '좋네요', '좋네용', '좋네욯',
       '좋놋르', '좋라요', '좋라용', '좋슴돠', '좋습다', '좋아 ', '좋아뇨', '좋아료', '좋아묘',
       '좋아쇼', '좋아야', '좋아어', '좋아여', '좋아열', '좋아영', '좋아오', '좋아옹', '좋아요',
       '좋아욕', '좋아욜', '좋아욤', '좋아욧', '좋아용', '좋아욪', '좋아욬', '좋아욮', '좋아욯',
       '좋아유', '좋아효', '좋앗엉', '좋앗음', '좋앙오', '좋앙요', '좋야오', '좋어여', '좋어요',
       '좋와요', '좋으욯', '좋은뎁', '좋음 ', '좋음요', '좋이르', '좋이요', '좋인영', '좋인요',
       '좋하욯', '죄어요', '죠아요', '죠앙 ', '준니솟', '줏즈스', '줗아요', '줗인요', '쥐츠덬',
       '쥬스용', '즈귿디', '즈니긑', '즈즌즈', '즌깁기', '즣아요', '지디딧', '지시잊', '지이임',
       '지지 ', '직아요', '진우너', '질겨요', '짓긋닏', '짙히힛', '짜요 ', '짜요뮤', '짱막 ',
       '짱맛있', '짱신선', '짱짱짱', '쪼아영', '쪼아요', '쪼아용', '쪼아유', '쪼아윤', '쫀맛탱',
       '찔겨요', '처파패', '첵스 ', '쳐7해', '초아요', '초초촟', '초촟쳐', '초호요', '초화요',
       '최고 ', '최고당', '최고임', '최애템', '쵸5툐', '츄파아', '칸둔틀', '콩느딐', '쾬차오',
       '쿠첸 ', '쿳굿긋', '큾드그', '키위굿', '톷룡툩', '툐9쳐', '튀김각', '튜추푸', '튵큐큐',
       '튼눅늣', '티기치', '퍼뎌냔', '퍽퍽 ', '퐇호할', '퓨홓호', '하뢀허', '하저냐', '할인가',
       '합니다', '핫딜굳', '핵꿀맛', '햐샤효', '햫퓨랴', '허낲추', '허라아', '허흎토', '혀츄후',
       '호료소', '호서롸', '호유허', '호초포', '호츄초', '호튜퓨', '호하냐', '호하허', '호호호',
       '혼합쌀', '혿보굣', '홀퍼요', '홉보보', '홎쇼8', '화이팅', '횿모효', '후져요', '후허륯',
       '훙 어', '훟훟읗', '흣듴둑', '히호허', '히히히', '힌맇룋', '힣히히'], dtype=object)

In [364]:
word[word.length_clean == 4]

                       content  prod_satis  ...  clean  length_clean
119              괜찮아요~~~~~~~~~           4  ...   괜찮아요             4
157              좋아요 ♡♡♡♡♡♡♡♡♡           5  ...   좋아요              4
167              짱이에요!!!!!!!!!           5  ...   짱이에요             4
724      맛있어요~~~~~~~~~~~~~~~~~           5  ...   맛있어요             4
904             그냥저냥~~~~~~~~~~           4  ...   그냥저냥             4
...                        ...         ...  ...    ...           ...
1694596            맛있어요~~~~~~~           5  ...   맛있어요             4
1694671            맛있어여~~~~~~~           5  ...   맛있어여             4
1695089             맛있어요~~~~~~           5  ...   맛있어요             4
1695303             맛있어요~~~~~%           5  ...   맛있어요             4
1695438             맛있어요~~~~~~           5  ...   맛있어요             4

[6634 rows x 6 columns]

In [365]:
word[word.length_clean == 5]

                content  prod_satis  ship_satis  length  clean  length_clean
219        좋아요 굿!!!!!ㅎㅎ           5           5      12  좋아요 굿             5
662      양호합니다~~~~~~~~~           4           4      14  양호합니다             5
1049         만족합니다~~~!!           3           3      10  만족합니다             5
1064      감사드려요!!!!!!!!           5           5      13  감사드려요             5
1340         보통입니다.....           3           4      10  보통입니다             5
...                 ...         ...         ...     ...    ...           ...
1694329     맛있어요 ㅎㅎㅎㅎㅎㅎ           5           5      11  맛있어요              5
1694387     잘먹을께요......           4           5      11  잘먹을께요             5
1694782  맛있어요 ^^^^#####           5           5      14  맛있어요              5
1695130     늘 시켜요......           5           5      11  늘 시켜요             5
1695204      만족합니다.....           5           5      10  만족합니다             5

[5771 rows x 6 columns]

In [366]:
word[word.length_clean == 6]

                     content  prod_satis  ...   clean  length_clean
62       잘 먹었어요~~~~~~~~~~~~~           4  ...  잘 먹었어요             6
120               좋아요ㅎㅎ굳굳굳ㅎㅎ           5  ...  좋아요굳굳굳             6
207               잘받았습니당ㅎㅎㅎㅎ           5  ...  잘받았습니당             6
463             밤고구마네여ㅜㅜㅜㅜㅜㅜ           3  ...  밤고구마네여             6
739               잘받았습니다★★★★           4  ...  잘받았습니다             6
...                      ...         ...  ...     ...           ...
1693564          너무 맛나요~~~~~           5  ...  너무 맛나요             6
1693696          잘받았습니다~~~~~           5  ...  잘받았습니다             6
1694569          잘받았습니다~~~~~           4  ...  잘받았습니다             6
1695358          그냥 그래요,,,,,           3  ...  그냥 그래요             6
1695511        잘 받았어요.......           5  ...  잘 받았어요             6

[7686 rows x 6 columns]

## 10자 미만인 것들은 리뷰에 0.5정도를 곱?

In [370]:
len(word[word.length_clean < 10]) / len(word) * 100

6.742947817936441

In [368]:
word[word.length_clean > 10]

                                                   content  ...  length_clean
0                                     생각보다 조금 얇지만 맛있게 먹을게요  ...            20
1                                          배송빠르고  맛도 괜찮아요.  ...            14
4                    싱싱하고 크기도 좋아요 근데 맛이 좀 덜들었네요좀난뒀다 먹어야겠어요  ...            37
5                    며칠동안 놔뒀다가 먹으니까 되게 맛있네요 다음에 또 시킬게요!!!!  ...            33
6                                          좀 실망스럽지만 잘 먹었어요  ...            15
...                                                    ...  ...           ...
1695504                                     다음에 또 주문 하겠습니다  ...            14
1695505                                  포장은 꼼꼼한데 냉동이 왔어요   ...            17
1695507  제가 먹어본건 아니구요  명절선물로 롯데 백화점에서진열상품확인후 온라인배송했습니다가...  ...            92
1695510                              맛있게 잘먹어서 다시 구매할 예정입니다  ...            21
1695512                                 아주 좋아요.소포장이라 더 좋네요  ...            17

[1154585 rows x 6 columns]